USE [accessNewPIP]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GIS_ALLSITES_LIVEDATA]
AS
SELECT     SYSTEM, GISPROPNUM, PropID, Name, LOCATION, SourceTable, GISACRES, AMPSDistrict, COUNCILDISTRICT, COMMUNITYBOARD, BOROUGH, Zip, GIS_Retired, 
                      SUBCATEGORY, PermitDistrict, TYPECATEGORY, JURISDICTION, NYSAssembly, NYSSenate, USCongress, Precinct
FROM         [GISDATA].ParksGIS.DPR.vw_GISAllSites AS vw_GISAllSites_1
GO


